name: relator
description: "retro games download."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_serializable: ^6.9.0
  permission_handler: ^11.3.1
  flutter_downloader: ^1.11.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/games/
    - assets/platform-list.json
